import img1 from "./ProductImages/img1.png";
import img2 from "./ProductImages/img2.png";
import img3 from "./ProductImages/img3.png";
import img4 from "./ProductImages/img4.png";
import img5 from "./ProductImages/img5.png";

const ProductsData = [
  {
    id: 1,
    title: "Remote Control Car",
    image: img1,
    category: "toys",
    description: "High speed RC car for kids",
    price: 199,
  },
  {
    id: 2,
    title: "Cute School Notebook Set",
    image: img2,
    category: "stationary",
    description: "Stylish notebooks for school use",
    price: 199,
  },
  {
    id: 3,
    title: "Birthday Surprise Gift Box",
    image: img3,
    category: "gifts",
    description: "Perfect gift for birthdays",
    price: 399,
  },
  {
    id: 4,
    title: "Building Blocks Toy Set",
    image: img4,
    category: "toys",
    description: "Creative learning blocks for kids",
    price: 599,
  },
  {
    id: 5,
    title: "Romantic Gift Combo",
    image: img5,
    category: "gifts",
    description: "Special gift for loved ones",
    price: 399,
  },
  {
    id: 6,
    title: "Toy Train Set",
    image: img2,
    category: "toys",
    description: "Fun toy train with tracks",
    price: 999,
  },
  {
    id: 7,
    title: "Soft Teddy Bear",
    image: img4,
    category: "toys",
    description: "Soft and cute teddy bear",
    price: 799,
  },
  {
    id: 8,
    title: "Kids Puzzle Game",
    image: img3,
    category: "toys",
    description: "Brain boosting puzzle game",
    price: 1099,
  },
  {
    id: 9,
    title: "Premium Pen Set",
    image: img1,
    category: "stationary",
    description: "Smooth writing pens set",
    price: 149,
  },
  {
    id: 10,
    title: "Color Marker Pack",
    image: img3,
    category: "stationary",
    description: "Colorful markers for drawing",
    price: 349,
  },
  {
    id: 11,
    title: "Office File Organizer",
    image: img4,
    category: "stationary",
    description: "Keep documents organized",
    price: 989,
  },
  {
    id: 12,
    title: "Study Kit Combo",
    image: img5,
    category: "stationary",
    description: "All-in-one study essentials",
    price: 399,
  },

  // 🔥 NEW PRODUCTS (13–22)

  {
    id: 13,
    title: "Mini Drone Toy",
    image: img1,
    category: "toys",
    description: "Flying drone with remote",
    price: 1499,
  },
  {
    id: 14,
    title: "Action Figure Hero Toy",
    image: img2,
    category: "toys",
    description: "Superhero action figure",
    price: 699,
  },
  {
    id: 15,
    title: "Barbie Doll Set",
    image: img3,
    category: "toys",
    description: "Beautiful doll for kids",
    price: 899,
  },
  {
    id: 16,
    title: "Luxury Gift Hamper",
    image: img4,
    category: "gifts",
    description: "Premium gift collection",
    price: 1999,
  },
  {
    id: 17,
    title: "Anniversary Gift Frame",
    image: img5,
    category: "gifts",
    description: "Memorable photo frame gift",
    price: 599,
  },
  {
    id: 18,
    title: "Greeting Card Combo Pack",
    image: img1,
    category: "gifts",
    description: "Cards for all occasions",
    price: 299,
  },
  {
    id: 19,
    title: "Gel Pen Pack",
    image: img2,
    category: "stationary",
    description: "Smooth gel pens",
    price: 199,
  },
  {
    id: 20,
    title: "Drawing Sketch Book",
    image: img3,
    category: "stationary",
    description: "Perfect for artists",
    price: 499,
  },
  {
    id: 21,
    title: "Kids Coloring Kit",
    image: img4,
    category: "stationary",
    description: "Fun coloring set",
    price: 299,
  },
  {
    id: 22,
    title: "Wooden Puzzle Toy",
    image: img5,
    category: "toys",
    description: "Eco-friendly puzzle toy",
    price: 399,
  },
];

export default ProductsData;
